

export enum ElementType {
  SOURCE_CODE = 'SOURCE_CODE',
  TEXT = 'TEXT',
  BIG_TITLE = 'BIG_TITLE',
  MEDIUM_TITLE = 'MEDIUM_TITLE',
  SMALL_TITLE = 'SMALL_TITLE',
  VERY_SMALL_TITLE = 'VERY_SMALL_TITLE',
  CONTENT = 'CONTENT',
  LIST = 'LIST',
  ATTACHMENT= 'ATTACHMENT',
  HYPERLINK = 'HYPERLINK',
}
